name: CI/CD Pipeline

on:
  push:
    branches: [main, develop, qa]
  pull_request:
    branches: [main, develop, qa]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy based on branch
        env:
          TARGET_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
        run: |
          
